### ISSUE TITLE
error in the logs

### ISSUE THREAD

**Issue by DaKnig** [wheremyfoodat/Gameboy-logs#2]
in the log for the `03-op\ sp\,hl.gb` file, you have an error- at when executing the instruction at DEF8 which is `inc sp`, when the value of `sp` is 15, you updated the flags from `0x00` to `0x20` which is incorrect. this instruction should not change the flags ever.

**Comment by wheremyfoodat** [comment]
This bug report is wrong
That instruction is not inc sp. It's LD HL, sp + 1
