### ISSUE TITLE
How do you run these tests?

### ISSUE THREAD

**Issue by fizaan** [wheremyfoodat/Gameboy-logs#4]
How do you test these ROMs? Where are the binaries? When I unzip the file I just see a text file. What do I do with that?? Can you add more instructions on how to run them? Thanks.

**Comment by griffi-gh** [comment]
You just compare them with the logs produced by your emulator....

**Comment by fizaan** [comment]
Ok but what test rom does each output map to? Also, Blarggs test ROMs have an infinite loop at the end of each rom: JR FE, so where do these results stop running?

**Comment by wheremyfoodat** [comment]
@fizaan The corresponding test rom is indicated by the file name. The results end right before the JR $FE

**Comment by fizaan** [comment]
@wheremyfoodat so you're saying that the output is mapped like this..?
Blargg1LYStubbed -> 01-special
Blargg2LYStubbed -> 02-interrupts
Blargg3LYStubbed  -> 03-op sp,hl
.... and so on...
Blargg11LYStubbed ->  11-op a,(hl)

**Comment by wheremyfoodat** [comment]
@fizaan Yes

**Comment by fizaan** [comment]
Got it. Thanks for the quick response. Btw I tried contacting you on discord with this username guccirodakino#1457. But it said the user doesn't exist?

**Comment by wheremyfoodat** [comment]
@fizaan Oh woops, my Nitro expired and my code changed. Try #0969

**Comment by fizaan** [comment]
@wheremyfoodat thanks buddy! You are very helpful. I will close this issue and contact you on discord if I encounter any more issues. Thanks again. Cheers.

**Comment by wheremyfoodat** [comment]
@fizaan <3
