### ISSUE TITLE
PC START ADDRESS values are inconsistent between logs

### ISSUE THREAD

**Issue by fizaan** [wheremyfoodat/Gameboy-logs#5]
@wheremyfoodat Hi again! I couldn't reach you on #969 so created another issue here. I noticed your test logs show inconsistent PC START ADDRESS values. For example below is the FIRST LINE in each of the test logs for 01-special, 02-interrupts, 03-sp,hl, 06-ld r,r (respectively), and, as you can see, PC is different in each case.  All my emulator output is starting at pc=0x100 so comparisons are failing in the first line for any log that doesn't start at pc=0x100

A: 01 F: B0 B: 00 C: 13 D: 00 E: D8 H: 01 L: 4D SP: FFFE PC: 00:0100 (00 C3 13 02)
A: 01 F: B0 B: 00 C: 13 D: 00 E: D8 H: 01 L: 4D SP: FFFE PC: 00:0101 (C3 13 02 CE) <---- should start at 0x100 ?
A: 01 F: B0 B: 00 C: 13 D: 00 E: D8 H: 01 L: 4D SP: FFFE PC: 00:0100 (00 C3 13 02)
A: 01 F: B0 B: 00 C: 13 D: 00 E: D8 H: 01 L: 4D SP: FFFE PC: 00:0101 (C3 13 02 CE) <-----should start at 0x100 ?

Why is PC start value inconsistent?

**Comment by griffi-gh** [comment]
doesn't matter, just ignore it

**Comment by fizaan** [comment]
@griffi-gh I understand it's not a big deal, but technically when writing test cases, such inconsistency in the PC start address cannot be ignored.
