### ISSUE TITLE
What is the `00:` part of PC?

### ISSUE THREAD

**Issue by jomag** [wheremyfoodat/Gameboy-logs#6]
Feels like I'm missing something obvious, but what is the first part of PC in the logs? `PC: 00:xxxx`. It's always 00 for the logs I've checked.

**Comment by wheremyfoodat** [comment]
It's memory banking-related, you can just print it as 00 and all of the logs will be happy.

**Comment by griffi-gh** [comment]
Current memory bank, it's always 0 in these tests
